// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtiHrcSHEepKqqmBdlgwfzgHan36pUXEQ',
    appId: '1:518933110924:web:a16b31beff6860962c5ba9',
    messagingSenderId: '518933110924',
    projectId: 'driversafemode',
    authDomain: 'driversafemode.firebaseapp.com',
    storageBucket: 'driversafemode.firebasestorage.app',
    measurementId: 'G-8WGY7FM33K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgVdvlr7iwNTVHSj_SuCAdrkWd5PJOerw',
    appId: '1:518933110924:android:01433f254041ef292c5ba9',
    messagingSenderId: '518933110924',
    projectId: 'driversafemode',
    storageBucket: 'driversafemode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7QdWl3bGSdgY2Z8orKIOVdKIPPNAxKxg',
    appId: '1:518933110924:ios:9aa11a5ff4bddfe12c5ba9',
    messagingSenderId: '518933110924',
    projectId: 'driversafemode',
    storageBucket: 'driversafemode.firebasestorage.app',
    iosBundleId: 'com.example.safeDriveMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtiHrcSHEepKqqmBdlgwfzgHan36pUXEQ',
    appId: '1:518933110924:web:8a11fd1108e0aef32c5ba9',
    messagingSenderId: '518933110924',
    projectId: 'driversafemode',
    authDomain: 'driversafemode.firebaseapp.com',
    storageBucket: 'driversafemode.firebasestorage.app',
    measurementId: 'G-YLBCM80W64',
  );
}
